# Generated by Django 4.2.7 on 2023-12-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='file',
            field=models.FileField(upload_to='car/media/uploads/'),
        ),
    ]
