# Generated by Django 4.2.7 on 2023-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
