# Generated by Django 4.2.7 on 2023-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
